force-app/main/default/objects/Student__c/fields/Scholarship_Rate__c.field-meta.xml
<CustomField>
    <fullName>Scholarship_Rate__c</fullName>
    <label>Scholarship Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ScholarshipRateService.cls
public class ScholarshipRateService implements Database.Batchable<sObject>{
	public Database.QueryLocator start(Database.BatchableContext bc) {
        return 	Database.getQueryLocator(
        	'Select Id FROM Student__c'
        );
    }
		
    public void execute(Database.BatchableContext BC, list<Student__c> students){
        for (Student__c s : students) {
            if (s.Scholarship__c == 'Unassigned') {
                s.Scholarship_Rate__c = 0;
            }
            else if (s.Scholarship__c == 'Regular') {
                s.Scholarship_Rate__c = 100;
            }
            else if (s.Scholarship__c == 'Increased') {
                s.Scholarship_Rate__c = 125;
            }
            else if (s.Scholarship__c == 'Academic') {
                s.Scholarship_Rate__c = 250;
            } else {
                s.Scholarship_Rate__c = -1;
            }
        }
        update students;
    }

    public void finish(Database.BatchableContext BC){}

}